# Generated by Django 5.2.8 on 2025-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('karta_tolov', models.IntegerField()),
                ('narhi', models.IntegerField()),
                ('tavsifi', models.CharField(max_length=150)),
            ],
        ),
    ]
