# Generated by Django 5.0.4 on 2025-12-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='sifati',
            field=models.BooleanField(null=True),
        ),
    ]
