# Generated by Django 5.0.4 on 2025-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platforma', '0002_tovar_sifati'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='super_narh',
            field=models.BooleanField(null=True),
        ),
    ]
