# Generated by Django 5.0.4 on 2025-12-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platforma', '0003_tovar_super_narh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragrph', models.CharField(max_length=50)),
                ('mini_info', models.TextField()),
            ],
        ),
    ]
